### ISSUE TITLE
Components and Plugins always have NEW flag on them

### ISSUE THREAD

**Issue by DavidFW1960** [custom-components/hacs#214]
## Version of HACS
0.11.1

## Describe the bug

In the Store, every component or plugin show the NEW flag
![image](https://user-images.githubusercontent.com/36390762/60474771-693c0480-9cb7-11e9-9ebc-adbe1cfefa72.png)

Wasn't that supposed to only happen after a new component was just added?
## Debug log

```text

Add your logs here.

```

**Comment by ludeeus** [comment]
This is expected.
https://github.com/custom-components/hacs/releases/tag/0.10.0

> _Every item in the store (that you have not installed) will have a "NEW" label after this release until you open them up for the first time._

you can manually change all of them by setting `new: false` in `.storage/hacs` then restart HA.

**Comment by capstan1** [comment]
I know you already closed this issue, but everytime I open HACS I get disturbed by all the "NEW" tags. And, they currently aren't telling the user what actually is new.
Like it is now, it serves more as an "unread" tag. But this is not what the user expects when reading "new". When seeing a "new" tag next to an integration the user will think that this integration was added to the store since he last visited. Not that he never clicked on it.

I just feel like it would be far more logical to add the new tab only when the plugin is seen for the first time/ to show it in the first session.

**Comment by DarkFox** [comment]
Just add a "Mark all as seen" at the bottom of the list, how can that clutter the interface?

Most new things aren't of interest to me, yet I end up having to click on each of them anyway (enduring the several-second load), to clear the "New" marker.

Sorry for what is basically a +1 post, but please reconsider this @ludeeus.

**Comment by marciogranzotto** [comment]
@ludeeus if there's a lot of users asking for it, how can it be bad for the user experience?
I get you don't want to add a button, but this can be implemented as an item on an overflow menu, or even just a service callable from HA. I see that there's already a function called `RemoveNewFlag` on `api.py`. Can't that be exposed in anyway??

**Comment by carlos-sarmiento** [comment]
I'd like to refresh this ask. Going into the `.storage` folder is not user friendly in any way. I like to use HACS to discover new integrations and plugins, but having to manually click on each item is a non-starter and I wonder how many users feel comfortable going into `.storage`
