### ISSUE TITLE
Req: make the custom repo's in settings tab clickable url to the source repo

### ISSUE THREAD

**Issue by raulvasquez** [custom-components/hacs#32]
It would be easier to access the repos on github if the name of the custom repo were clickable. Making the manually added repos into a hyperlink would save several clicks.

Currently you have to: 1) find the card in the overview or store, 2) click manage, 3) click repo.
vs.
settings > click

An alternative would be to add a repo button to the cards under store and overview. This could be done for install, reinstall, update, etc., and rename the manage link to "More Information"

**Comment by ludeeus** [comment]
But how about:
Make that link clickable, but instead of taking you to an external repo, you will get the view for that element?
IMO that makes more sense.

And about those extra buttons, the next version will say "More Information" for elements not installed, and "manage" for installed elements.
I actually want to remove that button and have the entire "card" clickable, similar to the hassio store, but that is way in the future.

**Comment by raulvasquez** [comment]
That also makes sense. The custom extensions I have enabled I do tend to rely on the github repos documentation since it can be advanced use. Just as long as it is clickable to somewhere would be an improvement imo.

**Comment by ludeeus** [comment]
This was included in the [`0.5.0` release](https://github.com/custom-components/hacs/releases/tag/0.5.0)
