### ISSUE TITLE
info.md not being displayed when repository info is not empty

### ISSUE THREAD

**Issue by peternijssen** [custom-components/hacs#52]
## Version of HACS
HACS version: 0.4.3
Home Assistant version: 0.93.2

## Describe the bug
According to the [documentation](https://custom-components.github.io/hacs/#note-for-developers) I can add a `info.md` file which is being rendered in the description of the card.
I've added this [file](https://github.com/peternijssen/lovelace-postnl-card/blob/master/info.md) but it doesn't show up.

I though it was maybe cache, but after reloading it still doesn't show up.

I've checked the code and if I understand correctly, it only shows up when the description of the repository is empty. See https://github.com/custom-components/hacs/blob/5f21c718dba9bfe73e0b3acc5830653378c8d40e/custom_components/hacs/frontend/views/repository.py#L77

I was expecting that this `info.md` was added nonetheless. So I am currently considering it a bug, but maybe it's intended functionality in which case I think the documentation should be updated.

**Comment by ludeeus** [comment]
The content of `info.md` is added regardless of the repository description :)

Your latest release did not contain an `info.md` it looks for that in the latest release, <https://github.com/peternijssen/lovelace-postnl-card/blob/0.10.0/info.md>

This is done so that the developer could potentially note breaking changes there and other info that is tied to a specific version.
After you publish a new release, then do a reload it should load your file as expected :)

**Comment by peternijssen** [comment]
Thanks! My mistake and thanks for clarifying.
