### ISSUE TITLE
HACS not showing up under integrations

### ISSUE THREAD

**Issue by iz3man** [custom-components/hacs#699]
Did the "regular" install of HACS 0.15.7 on HA (venv) 0.100 just now.
Copied hacs directory into custom_components, set all owner etc to homeassistant, then restarted.
Went into configuration, integrations, but HACS doesn't show up.
Then i found out, that it's the first entry with NO description:

![image](https://user-images.githubusercontent.com/11553674/66998148-05a5dd80-f0d4-11e9-8aac-251245a0a4fc.png)

If you click the first entry, it opens a window that looks like the following, but is missing some text entry and stuff. You can enter the token, it will accept, and then work (somehow)

![image](https://user-images.githubusercontent.com/11553674/66998190-19514400-f0d4-11e9-884e-2118c074ff32.png)

Then i enter my token, and i can see it in HA.
But it looks differently from the pictures in installation documentation:

![image](https://user-images.githubusercontent.com/11553674/66998299-4bfb3c80-f0d4-11e9-9a1c-56b97d44c588.png)

What do you think can cause this? Wrong permissions?
Thanks

**Comment by ludeeus** [comment]
Can be one of 2 issues:

1: You are missing the `.translations` directory
2: You need to clear your cache on the integration page.

**Comment by iz3man** [comment]
Thanks @ludeeus. Seems my copy process missed the .translation directory. It DOES work now. 
Still the "store" view doesn't look like it thought it has too. Or is it ok that way?

![image](https://user-images.githubusercontent.com/11553674/67008408-af439980-f0e9-11e9-8536-a9d7293692c2.png)

**Comment by pepeEL** [comment]
I have hassio with 0.100.2 version and now i try add integration HACS but in list not find it. I cleared all cache but nothing....

**Comment by ludeeus** [comment]
You need to install it @pepeEL Open a separate issue if you have issues with the installation.

@iz3man I'm not sure what you mean, that looks correct to me?

**Comment by pepeEL** [comment]
But install by copy it  ? But some time ago i see that in integration it will be show.

**Comment by iz3man** [comment]
@ludeeus In your documentation video it looks like this:

![image](https://user-images.githubusercontent.com/11553674/67010531-1c592e00-f0ee-11e9-84d6-a447bec6fa5c.png)

Notice the different grid, and the little icons this one has included?
Not that I care about it at all. but it's an indication that it's not 100% correct, and maybe this means there are other problems as well?!

**Comment by ludeeus** [comment]
**Separate issue* @pepeEL 

@iz3man I see, in my example I don't have any "New" repositories as you have, if you click the big blue button, it will look the same ;)

**Comment by crowbarz** [comment]
I had this issue as well, and it was caused because I unzipped hacs.zip directly into the HA custom_components directory, expecting (hoping?) that it would unzip everything into a hacs/ sub-directory. Arguably, https://hacs.xyz/docs/installation/manual implied that this would be the case: unlike on the Windows and macOS GUIs, unzip on Linux doesn't automatically extract into a sub-directory, so I needed to manually move all the unzipped files manually into a hacs/ sub-directory. The ".translations" sub-directory was missed because it's a dot file that is hidden by ls by default. (Interestingly there was also no HA log message flagging the missing directory, only the usual warning about the use of a custom integration.)

Would it be useful to add a note to the documentation that the archive needs to be manually unzipped into a sub-directory, and/or consider renaming the .translations to make this directory visible?

**Comment by P-Verbrugge** [comment]
Is there another solution to fix this? Have this issue as well, and the above suggestions don't work.

**Comment by marco-silva0000** [comment]
I had the same issue because i had unziped the file on custom_components and didn't create a new directory called hacs with the unziped stuff inside

**Comment by danielo515** [comment]
WTF, why do I need to clear the cache to see new integrations? By the way, using an incognito window works, but this is totally wrong (and it's probably a HASSIO fault)
