### ISSUE TITLE
Allow card / component updates to be flagged has having breaking changes

### ISSUE THREAD

**Issue by gadgetchnnel** [custom-components/hacs#7]
## Is your feature request related to a problem? Please describe.

A custom card or custom component may sometimes include breaking changes which will cause error messages (or the card/component to fail completely) if users update without checking the release notes and changing the configuration accordingly.

## Describe the solution you'd like

An additional property in the tracker JSON file (e.g. custom_card.json for a custom card) which marks the new version as a breaking change would allow this to be picked up, and the user prompted to view the release notes and update configuration before updating.

## Describe alternatives you've considered

Obviously, this should not be a replacement for effective communication with existing users of the card or component by updating any discussions where the card/component was originally announced (e.g. on the Home Assistant forums) but would be in addition in order to improve the user experience.

**Comment by ludeeus** [comment]
The developer can add an `info.md` file to the root of the repo, the content of that will show in the ElementView, there is also a changelog button that appears if there is an update.

There is an issue with this approach, this will show if you have the element installed or not, it does not filter on that.

I'm open for other suggestions, but before I add more logic I wish that more devs chime in on this, since itæs them who have to maintain something extra.

**Comment by ludeeus** [comment]
I'll close this one since I feel that using `info.md` is good enough for now, but I'm still open for other possibilities in a new FR :)
