### ISSUE TITLE
Change remote dependencies to local.

### ISSUE THREAD

**Issue by RmG152** [custom-components/hacs#72]
**Is your feature request related to a problem? Please describe.**
Not rly, just only focused on privacity.

**Describe the solution you'd like**
Change materialize.min.js and fontawesome from CDN to local folder to improve privacity.

**Comment by nervetattoo** [comment]
Yes yes yes! I can't stand external dependencies like this because it limits in what type of home setups you can use HA; For example in a cabin where you only set up a 4G connection when you want to do something. There is also the performance aspect, CDNs _can_ go down, you can have limited bandwidth or monthly usage.

I had lightning kill my fiber modem 5 days ago and am yet to receive a replacement due to long weekend, that really puts a test on how local my local home automation really is. Stuff like that happens and I would still expect to at least be able to open the HACS panel without relying on browser cache (even though I can't install anything)

**Comment by ludeeus** [comment]
Fixed in https://github.com/custom-components/hacs/releases/tag/0.7.0

https://github.com/custom-components/hacs/blob/926852a9dddf02f9b86a85a4261080d27cd7c438/custom_components/hacs/hacsviewbase.py#L27-L31

https://github.com/custom-components/hacs/tree/0.7.0/custom_components/hacs/frontend/elements
